/** 欢乐卡丁车的全部可调参数，单位统一使用内部赛道距离和毫秒。 */
export interface KartRacingGameConfig {
  trackLength: number
  maxSessionDurationMs: number
  finishCelebrationMs: number
  fixedStepMs: number
  maxFrameDeltaMs: number
  maxCatchUpSteps: number
  minSpeed: number
  cruiseSpeed: number
  maxSpeed: number
  accelerationResponseMs: number
  brakingResponseMs: number
  maxLateralSpeed: number
  steeringResponseMs: number
  lateralCenterDamping: number
  steeringNeutralThreshold: number
  throttleNeutralThreshold: number
  highSpeedSteeringMinFactor: number
  curveDriftFactor: number
  lateralLimit: number
  kartCollisionRadius: number
  collisionDepth: number
  hitSlowdownMs: number
  hitSlowdownFactor: number
  hitInvulnerabilityMs: number
  spawnLookAheadDistance: number
  stopSpawningBeforeEndDistance: number
  coinPatternSpacingMin: number
  coinPatternSpacingMax: number
  coinItemSpacing: number
  maxVisibleCoins: number
  obstacleSpacingMin: number
  obstacleSpacingMax: number
  itemSpacingMin: number
  itemSpacingMax: number
  shieldHitCount: number
  boostDurationMs: number
  boostFactor: number
  movementThreshold: number
  metricSampleIntervalMs: number
  coinPoolSize: number
  obstaclePoolSize: number
  itemPoolSize: number
  particlePoolSize: number
  debug: boolean
}

/** 默认参数优先保证动作平滑、预判充分和自然中心可完成训练。 */
export const defaultKartRacingGameConfig: KartRacingGameConfig = {
  trackLength: 1_000,
  maxSessionDurationMs: 120_000,
  finishCelebrationMs: 800,
  fixedStepMs: 1_000 / 60,
  maxFrameDeltaMs: 100,
  maxCatchUpSteps: 6,
  minSpeed: 10,
  cruiseSpeed: 14.4,
  maxSpeed: 20,
  accelerationResponseMs: 700,
  brakingResponseMs: 450,
  maxLateralSpeed: 1.08,
  steeringResponseMs: 280,
  lateralCenterDamping: 0.88,
  steeringNeutralThreshold: 0.06,
  throttleNeutralThreshold: 0.06,
  highSpeedSteeringMinFactor: 0.88,
  curveDriftFactor: 0.03,
  lateralLimit: 0.82,
  kartCollisionRadius: 0.13,
  collisionDepth: 3.8,
  hitSlowdownMs: 750,
  hitSlowdownFactor: 0.65,
  hitInvulnerabilityMs: 1_000,
  spawnLookAheadDistance: 90,
  stopSpawningBeforeEndDistance: 100,
  coinPatternSpacingMin: 36,
  coinPatternSpacingMax: 52,
  coinItemSpacing: 8,
  maxVisibleCoins: 18,
  obstacleSpacingMin: 90,
  obstacleSpacingMax: 125,
  itemSpacingMin: 150,
  itemSpacingMax: 220,
  shieldHitCount: 1,
  boostDurationMs: 2_500,
  boostFactor: 1.12,
  movementThreshold: 0.10,
  metricSampleIntervalMs: 40,
  coinPoolSize: 36,
  obstaclePoolSize: 12,
  itemPoolSize: 6,
  particlePoolSize: 80,
  debug: false,
}
